# ===============================
# Server
# ===============================
server.port=8082
spring.application.name=payment-orchestrator

# ===============================
# Database (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/paymentdb
spring.datasource.username=paymentuser
spring.datasource.password=paymentpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Redis (FIXED)
# ===============================
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=5000ms
spring.data.redis.connect-timeout=5000ms

# ===============================
# Kafka
# ===============================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=payment-orchestrator-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.acks=all

# ===============================
# Eureka
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# ===============================
# Observability (Tracing)
# ===============================
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# Ensure tracing is enabled
management.tracing.enabled=true

# Optional: Add trace IDs to your console logs to see them while debugging
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
# Enable tracing for the Producer (Orchestrator)
spring.kafka.template.observation-enabled=true
# Enable tracing for the Consumer (Fraud Service)
spring.kafka.listener.observation-enabled=true

# ===============================
# Logging
# ===============================
logging.level.root=INFO
logging.level.org.springframework.kafka=INFO
logging.level.org.flywaydb=INFO

# ===============================
# Security (Keycloak - LOCAL)
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/substrax

# ===============================
# Resilience4j - Retry (Kafka Producer)
# ===============================
resilience4j.retry.instances.paymentProducer.maxAttempts=3
resilience4j.retry.instances.paymentProducer.waitDuration=2s

resilience4j.retry.instances.paymentProducer.retryExceptions[0]=org.apache.kafka.common.errors.TimeoutException
resilience4j.retry.instances.paymentProducer.retryExceptions[1]=org.apache.kafka.common.errors.NetworkException
resilience4j.retry.instances.paymentProducer.retryExceptions[2]=java.net.ConnectException

