services:

  # ------------------------------------------------------------------------------
  # Utilities
  # ------------------------------------------------------------------------------
  eureka-server:
    container_name: eureka-server
    build:
      context: ../../services/eureka-server
      dockerfile: ../../services/eureka-server/Dockerfile
    image: substrax/eureka-server:latest
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - substrax-network

  api-gateway:
    container_name: api-gateway
    build:
      context: ../../services/api-gateway
      dockerfile: ../../services/api-gateway/Dockerfile
    image: substrax/api-gateway:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
      - keycloak
    networks:
      - substrax-network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak
    command: start-dev --import-realm
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

    volumes:
      - ./infra/keycloak/realm-export:/opt/keycloak/data/import

    depends_on:
      - keycloak-db
    networks:
      - substrax-network


  zipkin:
    image: ghcr.io/openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - substrax-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - substrax-network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: Yq3ZKcQvT2u6nQvZJx8fNg
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - ./infra/kafka-data:/var/lib/kafka/data
    networks:
      - substrax-network

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8085:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
    networks:
      - substrax-network

  # ------------------------------------------------------------------------------
  # Services
  # ------------------------------------------------------------------------------
  payment-orchestrator:
    container_name: payment-orchestrator
    build:
      context: ../../services/payment-orchestrator
      dockerfile: Dockerfile
    image: substrax/payment-orchestrator:latest
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - eureka-server
      - kafka
      - redis
      - payment-db
    networks:
      - substrax-network


  # ------------------------------------------------------------------------------
  # DB
  # ------------------------------------------------------------------------------
  keycloak-db:
    image: postgres:16
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - substrax-network


  payment-db:
    image: postgres:16
    container_name: payment-db
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: paymentuser
      POSTGRES_PASSWORD: paymentpass
    ports:
      - "5436:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    networks:
      - substrax-network


volumes:
  kafka_data:
  payment_db_data:
  keycloak_db_data:

networks:
  substrax-network:
    driver: bridge
