spring.application.name=eureka-server
server.port=8761

# Eureka server configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Disable self-preservation for local/dev
eureka.server.enable-self-preservation=false

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
