spring.application.name=eureka-server
server.port=8761

# Eureka server configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Docker / EC2 friendly
eureka.instance.hostname=eureka-server
eureka.server.enable-self-preservation=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
