# ===============================
# Application
# ===============================
spring.application.name=api-gateway
server.port=8080

# ===============================
# Eureka (Docker network)
# ===============================
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# ===============================
# Spring Cloud Gateway
# ===============================

# Enable service discovery based routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ---- EXPLICIT ROUTE (IMPORTANT) ----
spring.cloud.gateway.routes[0].id=payment-orchestrator
spring.cloud.gateway.routes[0].uri=lb://PAYMENT-ORCHESTRATOR
spring.cloud.gateway.routes[0].predicates[0]=Path=/payments/**

# ===============================
# Security (Keycloak)
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/substrax

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always

# ===============================
# Logging (DEBUG for routing & security)
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG

# ===============================
# Tracing
# ===============================
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.tracing.propagation.type=w3c,b3
